version: '3.4'

networks:
   frontend:
   backend:


services:
  catalog:
    image: events1/eventcatalogapi1
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment: 
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!) 
      ExternalCatalogUrl: http://localhost:7004


    ports: 
      - "7004:80"
    container_name: eventscatalogapi1
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events1/webmvc
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      CatalogUrl: http://catalog
      IdentityUrl: http://192.168.86.201:7900
      CallBackUrl: http://localhost:7600
    ports:
      - "7600:80"
    container_name: webshop1
    networks:
      - frontend
    depends_on: 
      - catalog
      - eventstokenserver


  
      
  eventstokenserver:   
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events1/eventstokenapi
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:7600
    ports:
      - "7900:80"
    container_name: eventstokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - eventstokensqlserver

      

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1452:1433"
    container_name: eventssqlserver
    networks: 
      - backend


  eventstokensqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1453:1433"
    container_name: eventsstokensqlserver
    networks: 
      - backend

