version: '3.4'

networks:
   frontend:
   backend:


services:
  catalog:
    image: events1/eventcatalogapi1
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment: 
      DatabaseServer: mssqlserver
      DatabaseName: EventCatalogDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!) 
      ExternalCatalogUrl: http://localhost:7004


    ports: 
      - "7004:80"
    container_name: eventscatalogapi1
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events1/webmvc
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
      CatalogUrl: http://catalog
    ports:
      - "7600:80"
    container_name: webshop1
    networks:
      - frontend
    depends_on: 
      - catalog






  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:latest"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1452:1433"
    container_name: eventssqlserver
    networks: 
      - backend

